### PR TITLE
Add role annotation for NF type

### LINKED ISSUE #3: What type role should NF's parameter have?
Currently, we let GHC infer

``` haskell
type role NF representational
```

I think there's a minor potential problem here. Suppose we have

``` haskell
data T = ...
newtype U = U T

instance NFData T where ...
instance NFData U where ... -- Something *different*
```

We can coerce from `NF T` (which is in `T`-normal form) to `NF U` (which claims to be in `U`-normal form). It's not quite clear to me whose problem this is. Should whoever defined `U` be expected to hide its constructor? Or should we have `type role NF nominal`?

In practice, I suspect this to come up rather rarely, since types are generally expected to have just one notion of normal form, but there could be exceptions out there.

### PR DESCRIPTION
**Pull request by treeowl**
Also add `nfCoercion` to work around the role annotation as
needed.

Fixes #3

### CODE REVIEW

**Comment by ezyang** [comment]
We should get a Travis build running >:)

Is the coercion really necessary? If you have the constructor `UnsafeNF` in scope you should have `forall a. NF a ~ a`, so you can derive `NF a ~ NF b` from `a ~ b`. I haven't tested yet.

(Role annotation looks fine to me)

**Comment by treeowl** [comment]
@ezyang, perhaps my documentation was insufficient. The trouble with importing `UnsafeNF` is that it has a _global_ effect in the importing module&mdash;every such coercion will be permitted. Using `nfCoercion`, the importing module can keep the effect _local_, preventing someone from accidentally performing an invalid coercion somewhere far from where they actually intend a coercion.

**Comment by ezyang** [comment]
Oops, I totally failed to read the module header. So, if I understand correctly, you could also put `nfCoercion` in `Internal`, the idea being that you hide the `UnsafeNF` constructor to rule out constructors. Well, putting it in a separate module seems fine to me.

**Comment by treeowl** [comment]
@ezyang, you certainly _could_ put it in `Internal` and hide the constructor, but it seems kinder to let the users decide which unsafe interface they want. I will try to deal with Travis today or tomorrow.

**Comment by ezyang** [comment]
Yes, I agree it's kinder.

Thanks for taking on Travis!

**Comment by treeowl** [comment]
Wait a second... I just realized that we can stick this in the Internal
module anyway; anyone who wants to use the coercion instead of the
constructor can just hide the constructor on import! I think that's
probably better than having a separate module.

**Comment by treeowl** [comment]
That's probably what you meant before; I misunderstood.

**Pull request merged**
